---
abstract: 'Moose Type Constraint classes for Structured Types'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Exception: 0.27
  Test::More: 0.70
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.08
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Structured
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.61
  MooseX::Types: 0.07
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
