---
abstract: 'Moose Type Constraint classes for Structured Types'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.27
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Structured
no_index:
  directory:
    - inc
    - t
requires:
  Devel::PartialDump: 0.10
  Moose: 0.63
  MooseX::Types: 0.08
  Sub::Exporter: 0.982
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
