---
abstract: 'Moose Type Constraint classes for Structured Types'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Exception: 0.27
  Test::More: 0.70
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.08
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Types-Structured
no_index:
  directory:
    - inc
    - t
requires:
  Devel::PartialDump: 0.07
  Moose: 0.63
  MooseX::Types: 0.08
  Sub::Exporter: 0.982
  perl: 5.8.0
version: 0.10
