use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
John
Napiorkowski
jjnapiork
Florian
Ragwitz
rafl
יובל
קוג
Yuval
Kogman
nothingmuch
Tomas
t0m
Doran
bobtfish
Robert
Sedlacek
rs
Ansgar
Burchardt
ansgar
Dave
Rolsky
autarch
Jesse
Luehrs
doy
Karen
Etheridge
ether
Ricardo
Signes
rjbs
phaylon
Stevan
Little
stevan
arcanez
justin
lib
MooseX
Meta
TypeConstraint
Structured
Types
MessageStack
TypeCoercion
Optional
OverflowHandler
